In [14]:
import requests
import pandas as pd

In [15]:
url = "https://newsapi.org/v2/top-headlines?sources=techcrunch&apiKey=fc27e5cbadad4e74b1b5cd0c8111eb37"

response = requests.get(url)
response.status_code

200

In [16]:
data = response.json()

In [17]:
data

{'status': 'ok',
 'totalResults': 10,
 'articles': [{'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Lauren Forristal',
   'title': "Bye-bye bots: Altera's game-playing AI agents get backing from Eric Schmidt | TechCrunch",
   'description': 'Autonomous, AI-based players are coming to a gaming experience near you, and a new startup, Altera, is joining the fray to build this new guard of AI Research company Altera raised $9 million to build AI agents that can play video games alongside other player…',
   'url': 'https://techcrunch.com/2024/05/08/bye-bye-bots-alteras-game-playing-ai-agents-get-backing-from-eric-schmidt/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/Minecraft-keyart.jpg?resize=1200,720',
   'publishedAt': '2024-05-08T15:14:57Z',
   'content': 'Autonomous, AI-based players are coming to a gaming experience near you, and a new startup, Altera, is joining the fray to build this new guard of AI agents.\r\nThe company announced Wednesday that it … [+6416 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Alex Wilhelm and Theresa Loconsolo',
   'title': '$450M for Noname, two billion-dollar rounds, and good news for crypto startups | TechCrunch',
   'description': "This morning on Equity, not only do we have good news for crypto founders, we're also digging into Akamai spending $450 million for API security firm Noname, and billion dollar deals from Wiz and Wayve.",
   'url': 'https://techcrunch.com/2024/05/08/450m-for-noname-two-billion-dollar-rounds-and-good-news-for-crypto-startups/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2023/07/GettyImages-942480316.jpg?resize=1200,835',
   'publishedAt': '2024-05-08T15:01:51Z',
   'content': 'Good news, crypto founders: Venture capital activity is picking up in your sector after falling to multi-year lows in late 2023. Put another way, venture folks appear more web3-bullish than before, e… [+1599 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Alex Wilhelm',
   'title': 'Watch: When did iPads get as expensive as MacBooks?',
   'description': 'Would you switch out your MacBook for an iPad with an M4 chip and OLED display? With the increase in price, Apple seems to be arguing these are comparable but we’re curious to see if consumers will make the change.',
   'url': 'https://techcrunch.com/2024/05/08/techcrunch-minute-when-did-ipads-get-as-expensive-as-macbooks/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/ipad-noplay.png?resize=1200,675',
   'publishedAt': '2024-05-08T14:52:26Z',
   'content': 'Apple’s iPad event had a lot to like. New iPads with new chips and new sizes, a new Apple Pencil, and even some software updates. If you are a big fan of Apple hardware, well, it was probably a good … [+1385 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Rebecca Bellan',
   'title': 'Uber promises member exclusives as Uber One passes $1B run-rate | TechCrunch',
   'description': 'Uber plans to deliver more perks to Uber One members, like member-exclusive events, in a bid to gain more revenue through subscriptions.\xa0 “You will see',
   'url': 'https://techcrunch.com/2024/05/08/uber-promises-member-exclusives-as-uber-one-passes-1b-run-rate/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1142304853-a.jpg?resize=1200,675',
   'publishedAt': '2024-05-08T14:41:36Z',
   'content': 'Uber plans to deliver more perks to Uber One members, like member-exclusive events, in a bid to gain more revenue through subscriptions.\xa0\r\nYou will see more member-exclusives coming up where members … [+4676 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Mike Butcher',
   'title': 'Checkfirst raises $1.5M pre-seed, applying AI to remote inspections and audits | TechCrunch',
   'description': 'Checkfirst enables businesses to schedule inspectors based on geographical location and qualifications, in addition to allowing for remote inspections.',
   'url': 'https://techcrunch.com/2024/05/08/checkfirst-raises-1-5m-pre-seed-applying-ai-to-remote-inspections-and-audits/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/Checkfirst-team.jpg?w=960',
   'publishedAt': '2024-05-08T13:02:12Z',
   'content': 'Weve all seen them. The inspector with a clipboard, walking around a building, ticking off the last time the fire extinguishers were checked, or if all the lights are working. They work in the TICC (… [+3279 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Paul Sawers',
   'title': 'UK challenger bank Monzo nabs another $190M as US expansion beckons | TechCrunch',
   'description': 'Monzo has raised another $190 million, as the challenger bank looks to expand its presence internationally — particularly in the U.S.',
   'url': 'https://techcrunch.com/2024/05/08/uk-challenger-bank-monzo-nabs-another-190m-at-5-2b-valuation/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/GettyImages-1259121938-e1715164252704.jpg?resize=1200,676',
   'publishedAt': '2024-05-08T12:34:05Z',
   'content': 'Monzo has raised another £150 million ($190 million), as the challenger bank looks to expand its presence internationally particularly in the U.S.\r\nThe new round comes just two months after Monzo rai… [+1960 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Brian Heater',
   'title': 'iRobot names former Timex head Gary Cohen as CEO | TechCrunch',
   'description': 'iRobot Tuesday announced the successor to longtime CEO, Colin Angle. Gary Cohen, who previous held chief executive role at Timex and Qualitor Automotive,',
   'url': 'https://techcrunch.com/2024/05/08/irobot-names-former-timex-head-gary-cohen-as-ceo/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/Screenshot-2024-05-08-at-7.19.50\u202fAM.jpg?resize=1200,919',
   'publishedAt': '2024-05-08T12:22:30Z',
   'content': 'iRobot Tuesday announced the successor to longtime CEO, Colin Angle. Gary Cohen, who previous held chief executive role at Timex and Qualitor Automotive, will be heading up the company, marking a maj… [+2120 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Devin Coldewey',
   'title': 'Google Deepmind debuts huge AlphaFold update and free proteomics-as-a-service web app | TechCrunch',
   'description': 'Google Deepmind has taken the wraps off a new version AlphaFold, their transformative machine learning model that predicts the shape and behavior of',
   'url': 'https://techcrunch.com/2024/05/08/google-deepmind-debuts-huge-alphafold-update-and-free-proteomics-as-a-service-web-app/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/alphafold-3-deepmind.jpg?resize=1200,675',
   'publishedAt': '2024-05-07T22:10:14Z',
   'content': 'Google Deepmind has taken the wraps off a new version AlphaFold, their transformative machine learning model that predicts the shape and behavior of proteins. AlphaFold 3 is not only more accurate, b… [+7069 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Tim De Chant',
   'title': 'Mycocycle uses mushrooms to upcycle old tires and construction waste | TechCrunch',
   'description': "The startup's fungi use their mycelium to consume oil-based rubbers and plastics, creating new bio-based materials in the process.",
   'url': 'https://techcrunch.com/2024/05/08/mycocycle-uses-mushrooms-to-upcycle-old-tires-and-construction-waste/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/GettyImages-1350655821.jpeg?resize=1200,796',
   'publishedAt': '2024-05-07T18:07:09Z',
   'content': 'Usually, when something starts to rot, it gets pitched in the trash. But Joanne Rodriguez wants to turn the concept of rot on its head by growing fungus on trash to turn it into something better.\r\nWe… [+4229 chars]'},
  {'source': {'id': 'techcrunch', 'name': 'TechCrunch'},
   'author': 'Kyle Wiggers',
   'title': 'Controversial drone company Xtend leans into defense with new $40M round | TechCrunch',
   'description': 'Xtend, a drone company heavily involved with defense customers, has raised a new round of capital to expand its operations.',
   'url': 'https://techcrunch.com/2024/05/08/controversial-drone-company-xtend-leans-into-defense/',
   'urlToImage': 'https://techcrunch.com/wp-content/uploads/2024/05/wildfire_drone_web.jpg?w=900',
   'publishedAt': '2024-05-07T18:01:34Z',
   'content': 'Close to a decade ago, brothers Aviv and Matteo Shapira co-founded Replay, a company that created a video format for 360-degree replays — the sorts of replays that have become part and parcel of majo… [+5398 chars]'}]}

In [19]:
df = pd.DataFrame(data)

In [20]:
df

  status  totalResults                                           articles
0     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
1     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
2     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
3     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
4     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
5     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
6     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
7     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
8     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...
9     ok            10  {'source': {'id': 'techcrunch', 'name': 'TechC...

In [21]:
df.to_csv("new.csv",index=False)

In [22]:
df['articles']

0    {'source': {'id': 'techcrunch', 'name': 'TechC...
1    {'source': {'id': 'techcrunch', 'name': 'TechC...
2    {'source': {'id': 'techcrunch', 'name': 'TechC...
3    {'source': {'id': 'techcrunch', 'name': 'TechC...
4    {'source': {'id': 'techcrunch', 'name': 'TechC...
5    {'source': {'id': 'techcrunch', 'name': 'TechC...
6    {'source': {'id': 'techcrunch', 'name': 'TechC...
7    {'source': {'id': 'techcrunch', 'name': 'TechC...
8    {'source': {'id': 'techcrunch', 'name': 'TechC...
9    {'source': {'id': 'techcrunch', 'name': 'TechC...
Name: articles, dtype: object

In [28]:
import requests
import pandas as pd
url = 'https://newsapi.org/v2/everything?q=bitcoin&apiKey=fc27e5cbadad4e74b1b5cd0c8111eb37'

In [29]:
response = requests.get(url)

In [30]:
data = response.json()
data

{'status': 'ok',
 'totalResults': 7218,
 'articles': [{'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'Popular Musician Loses Life Savings Through Malicious Crypto Wallet in Apple’s App Store',
   'description': 'The theft apparently combined a counterfeit app with a critical mistake by the musician.',
   'url': 'https://gizmodo.com/popular-musician-loses-life-savings-through-malicious-crypto-wallet-in-apples-app-store-2000745902',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/g-love-crypto-theft-1200x675.jpg',
   'publishedAt': '2026-04-13T21:25:17Z',
   'content': 'Musician G. Love lost his life savings after downloading a fake Ledger Live app from Apple’s Mac App Store, according to a post made to his X account. Noted blockchain investigator ZachXBT traced the… [+4424 chars]'},
  {'source': {'id': None, 'name': 'BBC News'},
   'author': None,
   'title': 'Lib Dems call for inquiry into Farage Bitcoin deal',
   'description': 'The Reform UK leader is a shareholder in British bitcoin company Stack and appeared in a promotional video.',
   'url': 'https://www.bbc.com/news/articles/cd9vgw2g3w2o',
   'urlToImage': 'https://ichef.bbci.co.uk/news/1024/branded_news/8ca9/live/2823e930-3766-11f1-a7e9-a1f2253df567.png',
   'publishedAt': '2026-04-13T20:08:38Z',
   'content': "In the promotional video to announce Stack's £2m Bitcoin purchase, Nigel Farage appeared alongside Kwasi Kwarteng, who served as UK chancellor for 38 days during Liz Truss's premiership."},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'AJ Dellinger',
   'title': 'Hollywood’s First Big Budget AI-Generated Movie Is About Bitcoin, of Course',
   'description': "Casey Affleck and Gal Gadot star in 'Paycheck: The Movie.'",
   'url': 'https://gizmodo.com/hollywoods-first-big-budget-ai-generated-movie-is-about-bitcoin-of-course-2000747573',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/gal_gadot-1200x675.jpg',
   'publishedAt': '2026-04-16T21:30:44Z',
   'content': 'One overhyped technology with dubious use cases deserves another, so it’s only right that the first big AI-generated film will focus on Bitcoin. An upcoming thriller called Bitcoin: Killing Satoshi, … [+2809 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'Crypto Investor at Center of Trump Corruption Allegations Now Sees Himself as ‘Victim’',
   'description': 'Justin Sun has accused Trump-affiliated World Liberty Financial of misconduct and a general lack of transparency.',
   'url': 'https://gizmodo.com/crypto-investor-at-center-of-trump-corruption-allegations-now-sees-himself-as-victim-2000745483',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/justin-sun-1200x675.jpg',
   'publishedAt': '2026-04-13T09:00:08Z',
   'content': 'Tron founder and crypto investor Justin Sun has accused Trump-affiliated World Liberty Financial of misconduct and a general lack of transparency. The early backer of the project previously sat at th… [+5050 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'Poll Finds 62% of Americans Don’t Trust Trump on Crypto',
   'description': "Despite his campaign's emphasis on crypto, one of Trump's signature pledges remains unfulfilled.",
   'url': 'https://gizmodo.com/poll-finds-62-of-americans-dont-trust-trump-on-crypto-2000753919',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/03/trump-getty-cabinet-march-26-2026-1200x675.jpg',
   'publishedAt': '2026-05-04T09:30:54Z',
   'content': 'Donald Trump’s vocal backing of the cryptocurrency industry during the 2024 campaign delivered substantial financial contributions from crypto backers and played a role in his return to the presidenc… [+4820 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': 'Ben Weiss',
   'title': 'Michael Saylor says remarks about selling Bitcoin were intended to jam short-sellers and ‘haters’',
   'description': 'Saylor, the chairman of Strategy, told Fortune that his comments about selling Bitcoin sought to protect his stock from crashing.',
   'url': 'https://finance.yahoo.com/markets/crypto/articles/michael-saylor-says-remarks-selling-154918323.html',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/5a8YrgfFHkAZvqvvFXvOWw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/fortune_175/0bce4eaf8f7e8de0fa24fd9a4c5b92ec',
   'publishedAt': '2026-05-08T15:49:18Z',
   'content': 'Michael Saylor is the worlds foremost Bitcoin buyer. You do not sell your Bitcoin, wrote the crypto billionaire in October. But, on a Tuesday earnings call, Saylor, whose company Strategy has accumul… [+2579 chars]'},
  {'source': {'id': None, 'name': 'BeInCrypto'},
   'author': 'Lockridge Okoth',
   'title': 'Billionaire Tim Draper Predicts Bitcoin Will Reach This Price in 18 Months',
   'description': 'Tim Draper recounts his Bitcoin losses and US Marshals auction win while predicting BTC could reach $250,000 in 18 months.',
   'url': 'https://beincrypto.com/tim-draper-bitcoin-price-prediction-for-18-months/',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/Q2zYKXFLTJay6SCltaYOWg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/beincrypto_us_662/7eeff894104145cd8b5e2926fffba860',
   'publishedAt': '2026-04-14T19:43:49Z',
   'content': 'Venture capitalist Tim Draper recounted his Bitcoin (BTC) history, renewing his call for a $250,000 price target.\r\nThe billionaire said his BTC journey began with a failed attempt to buy at $4 per co… [+1732 chars]'},
  {'source': {'id': None, 'name': 'NPR'},
   'author': 'Holly J. Morris',
   'title': "This week's quiz reveals a dramatic twist! OR DOES IT?",
   'description': "If you keep up with secret identities, you'll get at least one question right this week!",
   'url': 'https://www.npr.org/2026/04/10/g-s1-116787/arsenio-zendaya-colbert-bitcoin-news-quiz',
   'urlToImage': 'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5654x3180+0+1/resize/1400/quality/85/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F93%2F7a%2Fe2c772eb40d59461db1c301a20be%2Farsenio-stephen-zendaya.jpg',
   'publishedAt': '2026-04-10T09:01:00Z',
   'content': "Big news! Satoshi Nakamoto, the pseudonymous creator of bitcoin, has maybe been unmasked. Coupled with the recent revelation of Banksy's maybe true identity, two subjects have been swept from the tab… [+132 chars]"},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'David Pierce',
   'title': 'Fear and loathing at OpenAI',
   'description': "Sam Altman's tenure at OpenAI has been… messy. Messy to the point where Altman was briefly fired from his role as CEO, only to be reinstated days later, at which point he began reshaping the organization permanently. This week, The New Yorker published a deep…",
   'url': 'https://www.theverge.com/podcast/909621/openai-sam-altman-drama-vergecast',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/VRG_VST_0410_Site.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-04-10T12:23:18Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nOn The Vergecast: what it takes to be in charge of AI, some vibe-coding and DIY work, and Brendan Carr.\r\nOn The Vergecast: what it takes to be in charge of AI, s… [+3366 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Bruce Gil',
   'title': 'A Ransomware Negotiator Pleads Guilty to Being a Double Agent',
   'description': 'The Florida man helped BlackCat/ALPHV operators maximize their payouts.',
   'url': 'https://gizmodo.com/a-ransomware-negotiator-pleads-guilty-to-being-a-double-agent-2000749234',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/02/ransomware-2024-report-1200x675.jpg',
   'publishedAt': '2026-04-22T09:00:29Z',
   'content': 'A man who was supposed to help victims of ransomware attacks was actually helping the other side.\r\nAngelo Martino, a 41-year-old from Florida and a former ransomware negotiator, pleaded guilty to con… [+2526 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'U.S. government moving bitcoin tied to Bitfinex hack',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_774ffdb1-1848-43fa-96ac-e3c0d9e9ae85',
   'urlToImage': None,
   'publishedAt': '2026-04-17T17:23:34Z',
   'content': "If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Strategy Buys $2.54 Billion of Bitcoin, Most Since Late 2024',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_923d1d4b-a55e-462b-9a33-a52ea6e14992',
   'urlToImage': None,
   'publishedAt': '2026-04-20T14:10:34Z',
   'content': "If you click 'Accept all', we and our partners, including 250 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Kotaku'},
   'author': 'Zack Kotzer',
   'title': 'Bitcoin Thriller Billing Itself As First Studio-Quality AI-Generated Movie',
   'description': 'Gal Gadot, Casey Affleck, and Pete Davidson star in movie about previous snake oil phenomenon',
   'url': 'https://kotaku.com/bitcoin-thriller-billing-itself-as-first-studio-quality-ai-generated-movie-pete-davidson-gal-gadot-2000688877',
   'urlToImage': 'https://kotaku.com/app/uploads/2026/04/cryptoland.jpg',
   'publishedAt': '2026-04-19T19:56:51Z',
   'content': 'Its clear that Hollywood studios want to use AI in movie making. How to do so remains elusive, as the techs shortcomings become immediately obvious in practice and prohibitively expensive even for de… [+2223 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': 'Aniket Verma',
   'title': "Tim Draper Accurately Predicted Bitcoin At $10,000 — Now He Has 'Reason To Believe' It Will Go To $250,000 In 18 Months",
   'description': 'Venture capitalist Tim Draper predicted on Tuesday that Bitcoin will reach $250,000 in 18 months, and potentially higher, owing to inflationary pressures on ...',
   'url': 'https://finance.yahoo.com/markets/crypto/articles/tim-draper-accurately-predicted-bitcoin-193102134.html',
   'urlToImage': 'https://s.yimg.com/os/en/benzinga_79/4c341ad9e40cae69b25f20655544685c',
   'publishedAt': '2026-04-16T19:31:02Z',
   'content': 'Benzinga and Yahoo Finance LLC may earn commission or revenue on some items through the links below.\r\nVenture capitalist\xa0Tim Draper\xa0predicted on Tuesday that Bitcoin will reach $250,000 in 18 months,… [+9281 chars]'},
  {'source': {'id': None, 'name': 'Github.com'},
   'author': 'Pathos0925',
   'title': 'SatoshiGuesser – Roll for Bitcoin',
   'description': 'Roll for lost bitcoin. Contribute to Pathos0925/SatoshiGuesser development by creating an account on GitHub.',
   'url': 'https://github.com/Pathos0925/SatoshiGuesser',
   'urlToImage': 'https://opengraph.githubassets.com/5c4e5771cb062f8bd7f84af4494d3010db967a48e407fa290ed1e7468336d33d/Pathos0925/SatoshiGuesser',
   'publishedAt': '2026-04-30T16:29:58Z',
   'content': 'A slot-machine web game that "guesses" Satoshi Nakamoto\'s Bitcoin private\r\nkeys. The odds are astronomically remote (~1 in 5.27 × 10² per spin), but\r\nthe cryptography is real: every pull rolls a rand… [+8256 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'Michael Saylor’s Bitcoin Treasury Company Posts $12.5 Billion Loss, Boasts That People Are Still Giving It Money',
   'description': 'The company, Strategy, is effectively a levered play on bitcoin.',
   'url': 'https://gizmodo.com/michael-saylors-bitcoin-treasury-company-posts-12-5-billion-loss-boasts-that-people-are-still-giving-it-money-2000755338',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/05/michael-saylor-1200x675.jpg',
   'publishedAt': '2026-05-06T23:16:29Z',
   'content': 'Strategy, which is the $64 billion bitcoin treasury company led by Michael Saylor, has one overriding objective: acquire as much bitcoin as possible as quickly as possible. However, the firm posted 1… [+4380 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Bitcoin drives back toward $80K—but one billionaire may be fueling much of the rally',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_917594bb-7ddb-4606-9f3a-b9ca3e4836b9',
   'urlToImage': None,
   'publishedAt': '2026-04-27T18:32:13Z',
   'content': "If you click 'Accept all', we and our partners, including 250 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Iran Turns Strait of Hormuz Into Bitcoin Toll Booth: Will Crypto Hit $100,000 Again?',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_0a68f77a-5d85-4edc-ad08-d521bf87f96a',
   'urlToImage': None,
   'publishedAt': '2026-04-10T13:50:25Z',
   'content': "If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Bitcoin Price Will Hit $21M, Claims Michael Saylor, Following Strategy’s Latest $1B Purchase',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_0990a86b-7743-4944-a51c-aebe823f296b',
   'urlToImage': None,
   'publishedAt': '2026-04-14T14:52:18Z',
   'content': "If you click 'Accept all', we and our partners, including 251 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Xataka.com'},
   'author': 'Javier Pastor',
   'title': 'El NYT afirma haber encontrado a Satoshi Nakamoto y las pruebas son tan concluyentes como siempre. Es decir, poco o nada',
   'description': 'El 31 de octubre de 2008, alguien que se hacía llamar Satoshi Nakamoto publicó un documento de nueve páginas que proponía un sistema descentralizado de dienro electrónico. Aquel fue el nacimiento de bitcoin y de un fenómeno que ha hecho que se tambaleen os ci…',
   'url': 'https://www.xataka.com/criptomonedas/nyt-afirma-haber-encontrado-a-satoshi-nakamoto-pruebas-concluyentes-como-siempre-decir-poco-nada',
   'urlToImage': 'https://i.blogs.es/edad60/bitcoin-adm-back/840_560.jpeg',
   'publishedAt': '2026-04-10T11:30:13Z',
   'content': 'El 31 de octubre de 2008, alguien que se hacía llamar Satoshi Nakamoto publicó un documento de nueve páginas que proponía un sistema descentralizado de dienro electrónico. Aquel fue el nacimiento de … [+3983 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Tina Nguyen',
   'title': 'Trump’s posting even more AI-generated Trump-Jesus fanart',
   'description': "Hello and welcome to Regulator, a newsletter for Verge subscribers about Big Tech power plays in Washington and beyond. (And when I say beyond, I mean the great beyond, like Heaven, maybe.) If you've found your way to this newsletter from the wild, annual sub…",
   'url': 'https://www.theverge.com/column/912627/trump-jesus-ai-whcd-penguin-meme',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/trump-jesus-altered.png?quality=90&strip=all&crop=0,31.744282171397,100,36.511435657206',
   'publishedAt': '2026-04-15T19:53:53Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nPlus: what Werner Herzog thinks of the Trump penguin meme.\r\nPlus: what Werner Herzog thinks of the Trump penguin meme.\r\nby\r\nTina NguyenClose\r\nSenior Reporter, Wa… [+11519 chars]'},
  {'source': {'id': None, 'name': 'Microsiervos.com'},
   'author': 'alvy@microsiervos.com (Alvy)',
   'title': '¿Quieres petróleo? Paga peaje (en bitcoin)',
   'description': 'Durante la «tregua» de dos semanas anunciada en la guerra de Irán, el país persa ha planteado cobrar un peaje en criptomonedas a los petroleros que crucen el estrecho de Ormuz, a dólar el barril. En una rueda de prensa explicaron cómo funcionaría el asunto: l…',
   'url': 'https://www.microsiervos.com/archivo/economia/quieres-petroleo-paga-peaje-en-bitcoin.html',
   'urlToImage': 'https://img.microsiervos.com/images2026/tanker-hormuz.webp',
   'publishedAt': '2026-04-10T08:52:49Z',
   'content': 'Por @Alvy 10 de Abril de 2026\r\nDurante la «tregua» de dos semanas anunciada en la guerra de Irán, el país persa ha planteado cobrar un peaje en criptomonedas a los petroleros que crucen el estrecho d… [+1190 chars]'},
  {'source': {'id': None, 'name': 'Alcazarsec.com'},
   'author': 'Alcazar Security',
   'title': "How Monero's proof of work works",
   'description': 'Monero does not use a simple fixed hash like Bitcoin. Its proof of work, RandomX, turns mining into running random CPU-friendly programs over a large memory dataset, which is why it behaves so differently from ASIC-first systems.',
   'url': 'https://blog.alcazarsec.com/tech/posts/how-moneros-proof-of-work-works',
   'urlToImage': 'https://alcazarsec.com/og/alcazar-nisdwy-dms.png',
   'publishedAt': '2026-05-04T14:10:50Z',
   'content': 'Moneros proof of work is called RandomX.\r\nMonero does not ask miners to run the same tiny hash function over and over. It asks them to run a small random program on a virtual machine, hit memory hard… [+12588 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'Circle CEO Addresses Lack of Stablecoin Freezes During Crypto Thefts',
   'description': 'Circle will apparently not freeze its stablecoin without a court order or direction from law enforcement.',
   'url': 'https://gizmodo.com/circle-ceo-addresses-lack-of-stablecoin-freezes-during-crypto-thefts-2000745968',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/04/Jeremy-Allaire-1200x675.jpg',
   'publishedAt': '2026-04-14T09:00:22Z',
   'content': 'Circle CEO Jeremy Allaire indirectly addressed criticism over the stablecoin issuers handling of crypto thefts during a press conference in Seoul, according to a report in CoinDesk. He stated that Ci… [+5460 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Torpey',
   'title': 'April Was the Worst Ever Month on Record for Crypto Hacks',
   'description': 'Drift and Kelp DAO were the two most notable crypto hacks in April, combining for $579 million in losses.',
   'url': 'https://gizmodo.com/april-was-the-worst-ever-month-on-record-for-crypto-hacks-2000753890',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/10/gizmodo-social-1200x675-1.jpg',
   'publishedAt': '2026-05-03T15:29:12Z',
   'content': 'April was the worst month on record for crypto projects getting hacked, with 29 incidents tracked by crypto data provider DefiLlama. In terms of dollar value, $651 million in losses were recorded, wh… [+4944 chars]'},
  {'source': {'id': 'business-insider', 'name': 'Business Insider'},
   'author': 'wedwards@businessinsider.com (William Edwards)',
   'title': "Billionaire hedge fund investor Paul Tudor Jones says this is where he's eyeing his next big bet in markets",

In [32]:
df = pd.DataFrame(data)
df

   status  totalResults                                           articles
0      ok          7218  {'source': {'id': None, 'name': 'Gizmodo.com'}...
1      ok          7218  {'source': {'id': None, 'name': 'BBC News'}, '...
2      ok          7218  {'source': {'id': None, 'name': 'Gizmodo.com'}...
3      ok          7218  {'source': {'id': None, 'name': 'Gizmodo.com'}...
4      ok          7218  {'source': {'id': None, 'name': 'Gizmodo.com'}...
..    ...           ...                                                ...
91     ok          7218  {'source': {'id': None, 'name': 'Yahoo Enterta...
92     ok          7218  {'source': {'id': None, 'name': 'Yahoo Enterta...
93     ok          7218  {'source': {'id': None, 'name': 'Yahoo Enterta...
94     ok          7218  {'source': {'id': None, 'name': 'Yahoo Enterta...
95     ok          7218  {'source': {'id': None, 'name': 'Yahoo Enterta...

[96 rows x 3 columns]

In [35]:
df.to_csv('p1.csv',index=False)